version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "packages/a"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "packages/b"
    schedule:
      interval: "weekly"