version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "packages/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "services/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "services/db"
    schedule:
      interval: "weekly"