services:
  monorepo-api:
    image: monorepo-api
    container_name: monorepo-api
    platform: linux/amd64
    ports:
      - 3000:3000

    build:
      context: .
      dockerfile: ./services/api/Dockerfile
      platforms: 
        - linux/amd64

    env_file:
      - ./services/api/.env

  monorepo-db:
    image: monorepo-db
    container_name: monorepo-db
    platform: linux/amd64
    ports:
      - 3001:3000

    build:
      context: .
      dockerfile: ./services/db/Dockerfile
      platforms: 
        - linux/amd64

    env_file:
      - ./services/db/.env